name: Build-mt7621
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'mt7621/.config'

jobs:
  MT7621:
    runs-on: ubuntu-18.04
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git \
        libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex \
        uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo \
        libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool \
        autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply \
        python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar mkisofs
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        sudo df -h

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede

    - name: Download and Load custom configuration
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
        sed -i 's/192.168/10.0/g' package/base-files/files/bin/config_generate
        curl -fsSL https://raw.githubusercontent.com/tmr-github/OpenWrt_ActionTest/master/mt7621/.config >.config
        make defconfig

    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: When Multi-core compile failure will be rollback to Single core compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        cd bin/targets/*/*
        zip -r -o -q -9 mt7621.zip . -i *
        curl \
        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
        -H "Content-Type: $(file -b --mime-type mt7621.zip)" \
        --data-binary @mt7621.zip \
        "https://uploads.github.com/repos/tmr-github/OpenWrt_ActionTest/releases/36864904/assets?name=$(basename mt7621.zip)"
